### ISSUE TITLE
UpdateStatsAsync Overloads Not Clear

### ISSUE THREAD

**Issue by devhl-labs** [DiscordBotList/DBL-dotnet-Library#8]
There is an overload of UpdateStatsAsync that accepts int, int, array.  What are these parameters supposed to be?  The two int seem to be the same value, and I'm not sure what is expected in the array.

**Comment by velddev** [comment]
From the example shown below the idea is that it is a span of shards with their respective counts.

Make sure the array is equal size to `shardCount - indexShard`. 

```
// Update stats sharded   indexShard shardCount shards
await me.UpdateStatsAsync(24,        50,        new[] { 12, 421, 62, 241, 524, 534 });
```

**Comment by devhl-labs** [comment]
The overload that takes the guild count doesn't seem to work right. 

`await me.UpdateStatsAsync(_client.Guilds.Count); `

I'm passing in 28 as it is my test bot, but the website says 433.

**Comment by velddev** [comment]
The idea is that if you run a multi-process setup, you can use it to post shards individually from different processes without overriding the other shards.

Hence why you give a start, end and a payload with all counts. If you do not run a multi-process bot, I do not recommend you using it.
